spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./data/app.db

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
server:
  port: 8919

obs:
  receiver:
    port: 7779
    url: http://localhost:{{obs.receiver.port}}/obsState
